### ISSUE TITLE
Html textarea does not accept value property

### ISSUE THREAD

**Issue by frycz** [Thomazella/react-known-props#25]
## About

Html `textarea` properties (source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), `value` is not a valid one:

autocapitalize 

***Note***: This [autocapitalize] is a non-standard attribute supported by WebKit on iOS (therefore nearly all browsers running on iOS, including Safari, Firefox, and Chrome), which controls whether and how the text value should be automatically capitalized as it is entered/edited by the user. The non-deprecated values are available in iOS 5 and later

autocomplete
autofocus
cols
disabled
form
maxlength
minlength
name
placeholder
readonly
required
rows
spellcheck
wrap

`textarea` also accepts global attributes: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes.

### Possible solution

The correct attributes need to be added here https://github.com/Thomazella/react-known-props/blob/90885fbbcdac6eb4b88f74e195f8a8b48fbc1e0f/src/generated/reactHtmlElementsToPropsMap.js#L309-L331

**Comment by Thomazella** [comment]
so the correct attributes would be: 
```
autocomplete
autofocus
cols
disabled
form
maxlength
minlength
name
placeholder
readonly
required
rows
spellcheck
wrap
```
+ global attributes?

**Comment by diegohaz** [comment]
`value` is actually a valid prop on React `textarea` elements: https://reactjs.org/docs/forms.html#the-textarea-tag

**Comment by frycz** [comment]
Yes it is. Does this map https://github.com/Thomazella/react-known-props/blob/master/src/generated/reactHtmlElementsToPropsMap.js contain HTML attributes or react properties?

**Comment by Thomazella** [comment]
both I think. Goal here was to have all props _react_ recognizes

**Comment by frycz** [comment]
Ok, I reported the issue as we use your `getElementProps` function, which according to the docs returns "all props valid on the HTML/SVG element provided as an argument, plus all ARIA props, including role. Doesn't include event props".

Result of `getElementProps('textarea')` contains `value` which isn't valid HTML attribute but is accepted by React element. A question to you @Thomazella is if this is the intention of the function.

**Comment by Thomazella** [comment]
I think so, we've been using this lib with react. Are you saying that for your use case you'd rather only have valid HTML attributes?

**Comment by frycz** [comment]
Yea, this is what we expected. Anyway, we still use your lib with a small workaround. If `getElementProps` purpose is to give props accepted by React element then we are good, I thought that this is an error.

**Comment by Thomazella** [comment]
Maybe we should update docs at least, thoughts? or maybe rename the function, add jsdoc comments 🤔

**Comment by diegohaz** [comment]
I think the name of the library is enough. It's **react**-known-**props**. Can't be more descriptive. But if it causes confusion, emphasizing this in the readme is a good idea.
